#!/bin/bash

# For a (much) more advanced configuration example see:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="SF Pro:Semibold:17.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  updates=on
)
sketchybar --default "${default[@]}"

##### Adding aeropsace layouts #####

# Add the aerospace_workspace_change event we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change


# TODO: This is not used 
# remove it if not needed after update to config for workspace monitor assignment for < 3 displays
#
# Get the system monitor ID of the specified workspace. 
# Expects the workspace ID as the first argument
# Returns the monitor ID of the workspace
# returns nothing (empty string) if the workspace has no windows.
get_workspace_monitor_id() {
  local workspace_id="$1"
  # aerospace command that returns all windows in the workspace, formatted as only the system monitor ID
  # each workspace is 1 character long, so truncate the output to only the first character
  local aerospace_result=$(aerospace list-windows --workspace $workspace_id --format "%{monitor-appkit-nsscreen-screens-id}")
  # local aerospace_result=$(aerospace list-windows --workspace $workspace_id --format "%{monitor-id}")
  local monitor_id=${aerospace_result:0:1}
  echo $monitor_id
}

# TODO: Dumping this to see values and needed mappings for different monitor arrangements. 
# Remove when not needed anymore.
echo "-----"
echo "Aerospace Monitors"
echo "monitor-id | nsscreen-id | monitor name"
aerospace list-monitors --format "%{monitor-id}%{tab}| %{monitor-appkit-nsscreen-screens-id}%{tab}| %{monitor-name}"
# 1 | 2 | Built-in Retina Display                                                    
# 2 | 1 | BenQ PD3205UA
# 3 | 3 | VP2365 SERIES

echo "-----"
echo "NsSScreen to DirectDisplay?"
echo "nsscreen-id | DirectDisplayId"
swift -e 'import AppKit; import CoreGraphics; for (i, scr) in NSScreen.screens.enumerated() {
  let n = scr.deviceDescription[NSDeviceDescriptionKey("NSScreenNumber")] as! NSNumber
  print("\(i+1)    |  \(n.intValue)")
}'
# 1 2
# 2 1
# 3 4

echo "-----"
echo "SketchyBar Displays"
echo "Direct-display_id | arrangement-id"
sketchybar --query displays | jq -r '.[] | "\(.["DirectDisplayID"])      |  \(.["arrangement-id"])"'
# 2 1                                                                                
# 4 2
# 1 3

echo "-----"


# TODO: Do this dynamically -- detect monitor count and which monitors.
# MONITOR SETUP MAPPINGS
# Aeropsace id to sketchybar arrangement id

# Three monitor setup Left to right: Built In, main, secondary
declare -a monitors=([1]="3" [2]="1" [3]="2")

# TODO: Two monitor setup (just two external displays: main and secondary)
# TODO: Two monitor setup (built-in and 1 external: built in display and main)

# Add workspaces for all monitors
for monitor_id in $(aerospace list-monitors --format "%{monitor-id}"); do
# for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
  for sid in $(aerospace list-workspaces --monitor "$monitor_id"); do
  # for sid in $(aerospace list-workspaces --all); do
    # Determine which display this workspace should be shown on
    # display_id=$(get_workspace_monitor_id $sid)
    display_id=${monitors[$monitor_id]}
    echo "$monitor_id | $display_id | $sid"

    sketchybar --add item space.$sid left \
      --set space.$sid display="$display_id" \
      --subscribe space.$sid aerospace_workspace_change \
      --set space.$sid \
      drawing=on \
      background.color=0x44ffffff \
      background.corner_radius=5 \
      background.drawing=on \
      background.border_color=0xAAFFFFFF \
      background.border_width=0 \
      background.height=25 \
      icon="$sid" \
      icon.padding_left=10 \
      icon.shadow.distance=4 \
      icon.shadow.color=0xA0000000 \
      label.font="sketchybar-app-font:Regular:16.0" \
      label.padding_right=20 \
      label.padding_left=0 \
      label.y_offset=-1 \
      label.shadow.drawing=off \
      label.shadow.color=0xA0000000 \
      label.shadow.distance=4 \
      click_script="aerospace workspace $sid" \
      script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  done
done

echo " ------- "

# Load Icons on startup for all monitors
for monitor in $(aerospace list-monitors --format "%{monitor-appkit-nsscreen-screens-id}"); do
  for sid in $(aerospace list-workspaces --monitor "$monitor" --empty no); do
    apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')
    echo "$apps"
    sketchybar --set space.$sid drawing=on

    icon_strip=" "
    if [ "${apps}" != "" ]; then
      while read -r app; do
        icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
      done <<<"${apps}"
    else
      icon_strip=""
    fi
    echo "-> $icon_strip"
    sketchybar --set space.$sid label="$icon_strip"
  done
done


#front app
source "$CONFIG_DIR/items/front_app.sh"


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
